// Competitions & awards — edit this file to update the Competitions section
// result: 'winner' → mauve border + filled badge; 'finalist' / 'participant' → subtle badge
// image: optional — if provided, card shows a cover area; if absent, compact icon+badge layout
// gradientPreset: color of the cover area if no image — 'gold' | 'mauve' | 'slate' | 'teal' | 'rose' | 'navy' | 'amber' | 'green'

import type { Competition } from '@/lib/types';

export const competitions: Competition[] = [
  {
    title: 'Climate Solutions Big Picture',
    organization: 'Dempsey Startup Competition, UW',
    type: 'startup',
    result: 'winner',
    resultLabel: 'Winner — $5,000',
    year: '2026',
    description: 'Awarded to LEAF, a marketplace platform connecting the reforestation supply chain through a Plant Resilience Certification grounded in eco-physiological testing and data tools. Recognized for outstanding innovation, we built a live AI-powered prototype and pitched to 250+ judges in a single afternoon.',
    gradientPreset: 'green',
  },
  {
    title: 'Value Guru Award',
    organization: 'MishiPay',
    type: 'award',
    result: 'winner',
    resultLabel: 'Top 1% Performer',
    year: '2025',
    description: 'Quarterly recognition for impact across client delivery and cross-functional teamwork. Strengthened stakeholder management and decision-making while building a global retail platform alongside engineering, QA, and customer success.',
    gradientPreset: 'amber',
  },
  {
    title: 'Future Female Leaders Award',
    organization: 'IESE Business School',
    type: 'award',
    result: 'finalist',
    resultLabel: 'Semi-Finalist ×2',
    year: '2023 & 2024',
    description: 'Recognized twice as a semi-finalist among young professional women aligned with IESE\'s mission of positive societal impact. Awardees are invited to a conference in Barcelona with networking, career development sessions, and MBA scholarship opportunities.',
    gradientPreset: 'gold',
  },
  {
    title: 'Peer-to-Peer Recognition Award',
    organization: 'JP Morgan Chase',
    type: 'award',
    result: 'winner',
    resultLabel: 'Multiple Awards',
    year: '2022',
    description: 'Received multiple peer-nominated awards from teammates recognizing exceptional collaboration, teamwork, and innovative contributions during tenure at JP Morgan Chase.',
    gradientPreset: 'rose',
  },
  {
    title: 'Wintathon',
    organization: 'LinkedIn',
    type: 'hackathon',
    result: 'finalist',
    resultLabel: 'Finalist',
    year: '2019',
    description: 'Selected for exceptional problem-solving skills as one of 60 women across India to develop innovative products in a team of three. Qualified to present to LinkedIn\'s leadership team in Bangalore.',
    gradientPreset: 'navy',
  },
  {
    title: 'Codeathon 2019',
    organization: 'Fidelity Investments',
    type: 'hackathon',
    result: 'winner',
    resultLabel: 'Winner',
    year: '2019',
    description: 'Won the annual coding contest for the Leap Graduate Internship program. Outperformed numerous teams by solving complex coding problems under time constraints, earning a prize and recognition at the Bangalore and Chennai offices.',
    gradientPreset: 'amber',
  },
  {
    title: 'Smart India Hackathon',
    organization: 'Government of India',
    type: 'hackathon',
    result: 'finalist',
    resultLabel: 'Finalist',
    year: '2019',
    description: 'Selected as a finalist among 200K+ students and 37K+ ideas to promote PM\'s Digital India vision. Submitted an IoT-based product concept in the healthcare domain in both software and hardware categories.',
    gradientPreset: 'slate',
  },
  {
    title: 'FREQUENZZ — IDEAZ International Paper Presentation',
    organization: 'IIT Roorkee (Electrical Engineering)',
    type: 'hackathon',
    result: 'finalist',
    resultLabel: '2nd Place',
    year: '2019',
    description: 'Secured 2nd place at an international paper presentation competition among 60 participants, presenting on the feasibility of an IoT-based solution in healthcare.',
    gradientPreset: 'mauve',
  },
  {
    title: 'Microsoft Codess Mentee',
    organization: 'Microsoft',
    type: 'award',
    result: 'participant',
    resultLabel: 'Selected Mentee',
    year: '2018',
    description: 'Selected as one of 150 women across India for Microsoft\'s initiative promoting gender diversity in engineering. Gained access to networking events and mentorship, and built an application under the program.',
    gradientPreset: 'teal',
  },
  {
    title: 'Learn IT Girl Scholar',
    organization: 'Learn IT Girl',
    type: 'award',
    result: 'winner',
    resultLabel: 'Scholar · Top 6',
    year: '2017',
    description: 'Selected as one of 20% of global applicants for a mentorship program by Google Anita Borg Scholarship recipients. My project ranked in the top 6 out of 100+ projects, featured on the program\'s third-edition website.',
    gradientPreset: 'green',
  },
  // {
  //   title: 'Intra-Hostel Foosball Tournament',
  //   organization: 'IIT Roorkee — Student Affairs Council',
  //   type: 'award',
  //   result: 'winner',
  //   resultLabel: '1st Place',
  //   year: '2018',
  //   description: 'Secured 1st prize in the intra-Bhawan Foosball competition at Sarojini Bhawan during the annual intra-hostel sports tournament organized by the Student Affairs Council.',
  //   gradientPreset: 'mauve',
  // },
];
