// Projects — edit this file to update your projects section
// featured: true → appears in the AI Agents featured cards (large layout)
// category drives the filter tabs — single value or array for multiple tabs:
// 'product' | 'ops' | 'ml' | 'finance' | 'ai'  e.g. category: ['product', 'finance']
//
// type: 'internal' → links to /projects/[slug] (needs a matching MDX file in src/content/projects/)
// type: 'external' → opens link in a new tab (use for Notion docs, decks, GitHub repos, etc.)

import type { Project } from '@/lib/types';

export const projects: Project[] = [
  {
  title: 'From Queue to Checkout in 20 Seconds',
  company: 'Mishipay',
  description: 'Led product discovery and the PRD for RFID self-checkout at Scotiabank Arena, replacing a 90-second barcode checkout that was suppressing game-day merchandise sales with a sub-20-second kiosk flow.',
  tags: ['Product Discovery', 'PRD', 'Pilot Management', 'Retail Tech'],
  category: ['product', 'ml'],
  link: '/projects/mlse-rfid-checkout',
  type: 'internal',
  featured: true,
  metrics: [
    { value: '78%', label: 'Faster checkout' },
    { value: '$1.1M', label: 'Incremental revenue' },
    { value: '+55%', label: 'YoY retail revenue growth' },
  ],
  externalLinks: [
    { label: 'Read Article', url: 'https://mishipay.com/case-study/mlse-case-study/' },
  ],
  },
  {
  title: 'Saving a $520K UAE Retail Contract',
  company: 'Mishipay',
  description: 'Led a 15-day cross-company investigation into payment discrepancies threatening Mishipay\'s largest UAE client, diagnosing a root cause across three organizations and turning a churn-risk account into a contract expansion.',
  tags: ['Root Cause Analysis', 'Stakeholder Management', 'Python', 'Client Relationship'],
  category: ['ops', 'ml', 'finance'],
  link: '/projects/grandiose-payment-reconciliation',
  type: 'internal',
  featured: true,
  metrics: [
    { value: '$520K', label: 'Revenue saved + generated' },
    { value: '15 days', label: 'End-to-end resolution' },
    { value: '0%', label: 'Discrepancy rate (from 12%)' },
  ],
  },
  {
  title: 'Platform Cost Attribution Initiative',
  company: 'JP Morgan Chase',
  description: 'Designed a structured naming standard enforced at the platform gate across private cloud platforms, fixing workload cost attribution and turning a 22-day manual billing reconciliation into a 4-day automated process.',
  tags: ['Platform Product', 'FinOps', 'Infrastructure', 'Governance'],
  category: ['product', 'finance', 'strategy'],
  link: '/projects/jrn-resource-naming',
  type: 'internal',
  featured: true,
  metrics: [
    { value: '$3.8M', label: 'Charges correctly allocated' },
    { value: '97%', label: 'Attribution coverage (from 61%)' },
    { value: '82%', label: 'Faster billing cycle' },
  ],
  },
  {
  title: 'SolWeave: A Blue Ocean Strategy for REI',
  company: 'UW Foster',
  description: 'Designed and pitched a new product category for REI, a solar-integrated rainfly tent cover, using Blue Ocean Strategy tools to find uncontested market space, then built the full go-to-market plan: segmentation, positioning, pricing, and channel strategy.',
  tags: ['Blue Ocean Strategy', 'Product Strategy', 'Go-to-Market', 'Market Sizing'],
  category: ['product', 'strategy'],
  link: 'https://drive.google.com/drive/folders/1p8cjUDaknqEUmrkRwgj5zj0NEnJ6iWaW?usp=sharing',
  type: 'external',
  featured: false,
  metrics: [
    { value: '$270M', label: 'Year-1 addressable revenue potential' },
    { value: '770K', label: 'Target early-adopter users' },
    { value: '$249', label: 'Proposed price vs. $370+ value delivered' },
  ],
},
  {
  title: 'A Data Pipeline That Never Blocks Checkout',
  company: 'Mishipay',
  description: 'Architected a hybrid batch + event-driven ETL pipeline on Airflow and Kafka serving 10+ retail clients with wildly different source systems, designed so a backend pipeline failure never stops a customer mid-checkout.',
  tags: ['Data Architecture', 'Apache Airflow', 'Kafka', 'Failure Handling'],
  category: ['ops','ml'],
  link: '/projects/etl-pipeline',
  type: 'internal',
  featured: false,
  metrics: [
    { value: '$46.8M', label: 'Transaction value processed' },
    { value: '10+', label: 'Retail clients onboarded' },
    { value: '4.4M', label: 'Transaction capacity (load-tested)' },
  ],
},
{
  title: 'Zillow + Yelp: A $2.5B Acquisition Proposal',
  company: 'UW Foster',
  description: 'Built the full M&A business case for Zillow to acquire Yelp — valuation, synergy modeling, purchase price allocation, and integration roadmap — presented as an acquisition proposal to a simulated Yelp Board of Directors.',
  tags: ['M&A Strategy', 'Valuation', 'DCF Modeling', 'Financial Analysis'],
  category: ['finance', 'strategy'],
  link: 'https://docs.google.com/presentation/d/1MHpCdB2udAhvgSQtLhSJdpQHaG9yEnsO/edit?usp=sharing&rtpof=true&sd=true',
  type: 'external',
  featured: false,
  metrics: [
    { value: '$2.5B', label: 'Recommended acquisition price' },
    { value: '$625M+', label: 'Year-1 incremental revenue' },
    { value: '$630M', label: '3-year synergy NPV' },
  ],
  },
  {
  title: 'Cost vs. Conscience: Weighing Strategy Against the Numbers',
  company: 'UW Foster',
  description: 'Argued how executives should balance qualitative factors, environmental sustainability, talent allocation, customer trust, competitive optionality, against financial analysis when making decisions like Etsy\’s cloud migration, drawing on team work experience.',
  tags: ['Strategic Decision-Making', 'Financial Analysis', 'Case Study'],
  category: ['finance', 'strategy'],
  link: 'https://drive.google.com/drive/folders/1bhITKAtiX02QXr7eQRHRAUhSmslN8-lC?usp=sharing',
  type: 'external',
  featured: false,
},
  {
  title: 'Automated Fault Detection & Alerting',
  company: 'JP Morgan Chase',
  description: 'Designed a two-layer observability system, synthetic canary testing plus conditional alert routing, that pinpoints whether a marketplace failure is a platform or service-provider fault in minutes instead of hours.',
  tags: ['Platform Product', 'Observability', 'Infrastructure', 'Incident Response'],
  category: 'product',
  link: '/projects/osb-observability',
  type: 'internal',
  featured: false,
  metrics: [
    { value: '97%', label: 'Faster fault detection' },
    { value: '75%', label: 'Faster resolution' },
    { value: '650 hrs', label: 'Triage time reclaimed/yr' },
  ],
},
  {
  title: 'Self-Serve Vendor Certification System',
  company: 'JP Morgan Chase',
  description: 'Designed and built an async certification suite that every service provider must pass before listing on the internal marketplace — testing the full OSB lifecycle, enforcing compliance, and making onboarding fully self-serve.',
  tags: ['Platform Product', 'Developer Experience', 'Compliance', 'Infrastructure'],
  category: ['product', 'ops'],
  link: '/projects/osb-certification',
  type: 'internal',
  featured: false,
  metrics: [
    { value: '85%', label: 'Faster time-to-list' },
    { value: '12 wks', label: 'Reclaimed per provider' },
  ],
},
{
  title: 'Cutting Post Office Wait Times by 65% — No New Hires',
  company: 'UW Foster',
  description: 'Ran a live site visit and built a discrete-event simulation of a USPS lobby to diagnose a queueing bottleneck, then modeled four intervention scenarios to find a zero-headcount fix.',
  tags: ['Process Simulation', 'Queueing Theory', 'Operations Research', 'Site Observation'],
  category: 'ops',
  link: 'https://drive.google.com/drive/folders/1_Lou28MAS85U8I3HIRKvGi9LASsUfq43?usp=sharing',
  type: 'external',
  featured: false,
  metrics: [
    { value: '65%', label: 'Reduction in average wait time' },
    { value: '0', label: 'Additional headcount required' },
    { value: '96.5% → 84.5%', label: 'Counter utilization after rerouting' },
    { value: '9 pts', label: 'Self-service routing shift (11% → 20%)' },
  ],
},
{
  title: 'One Platform, Four Very Different Retailers',
  company: 'Mishipay',
  description: 'Defined the platform strategy distinguishing core, configurable, and client-specific layers, letting one system serve a duty-free airport retailer, a sports venue, a supermarket, and a US grocery giant without destabilizing the others.',
  tags: ['Platform Strategy', 'Product Architecture', 'Stakeholder Management'],
  category: ['product', 'ops', 'strategy'],
  link: '/projects/mishi-platform-strategy',
  type: 'internal',
  featured: true,
  metrics: [
    { value: '4', label: 'Structurally different clients' },
    { value: '3', label: 'Continents' },
    { value: '$3.3M+', label: 'Combined revenue impact' },
  ],
},
{
  title: 'Where National Park Funding Doesn\’t Match Ecological Risk',
  company: 'UW Foster',
  description: 'Merged NPS biodiversity, visitation, and funding datasets across 53 national parks to build a composite Ecological Stress Index, exposing a systemic mismatch between which parks carry the greatest conservation burden and which actually get funded.',
  tags: ['Data Analytics', 'SQL', 'Composite Index Modeling', 'Policy Research'],
  category: 'ml',
  link: 'https://drive.google.com/drive/folders/14Rj4iTfziJSQQCYZvsoHbgGrA_VRgOm4?usp=sharing',
  type: 'external',
  featured: false,
  metrics: [
    { value: '53', label: 'National parks analyzed' },
    { value: '3.3x', label: 'More biodiverse purity in low- vs. high-traffic parks' },
    { value: '$495K', label: 'Funding gap per at-risk species, best vs. worst-funded park' },
    { value: '7', label: 'Parks flagged as highest ecological risk' },
  ],
},
{
  title: 'Maximizing Concert Profit by Protecting the Right Seats',
  company: 'UW Foster',
  description: 'Applied the newsvendor model to a two-wave concert ticket sale to find the optimal number of seats to hold back for Premium buyers, then built and validated a Monte Carlo simulator against the analytical solution.',
  tags: ['Revenue Management', 'Newsvendor Model', 'Decision Analysis', 'Monte Carlo Simulation'],
  category: ['ops', 'ai'],
  link: 'https://docs.google.com/document/d/1GOFrnYj6H3SzplzZH9m6EjQrr0PwaAj0/edit?usp=sharing&ouid=100358671322377485595&rtpof=true&sd=true',
  type: 'external',
  featured: false,
  metrics: [
    { value: '150 / 500', label: 'Optimal seats protected for Premium' },
    // { value: '0.538', label: 'Critical ratio at baseline pricing' },
    { value: '$37,870', label: 'Expected contribution margin' },
    { value: '<1%', label: 'Simulation vs. analytical model error' },
  ],
},
  // {
  //   title: 'AI Compliance Automation Engine',
  //   company: 'JP Morgan Chase',
  //   description: 'Built an ML-powered engine that auto-flags high-risk transactions and routes edge cases to analysts, replacing a fully manual 4-day batch review process.',
  //   tags: ['AI/ML', 'Product Strategy', 'Compliance'],
  //   category: 'ai',
  //   link: '/projects/ai-compliance-engine',
  //   type: 'internal',
  //   featured: true,
  //   metrics: [
  //     { value: '40%', label: 'Faster reviews' },
  //     { value: '28%', label: 'Fewer false positives' },
  //     { value: '3', label: 'Business lines' },
  //   ],
  // },
  // {
  //   title: 'Payments Operations Dashboard',
  //   company: 'JP Morgan Chase',
  //   description: 'Designed and shipped a real-time ops dashboard that gave the payments team full visibility into transaction health, SLA breaches, and exception queues.',
  //   tags: ['Operations', 'Data', 'Tooling'],
  //   category: 'ops',
  //   link: '/projects/payments-ops-dashboard',
  //   type: 'internal',
  //   featured: true,
  //   metrics: [
  //     { value: '2×', label: 'Faster resolution' },
  //     { value: '60%', label: 'Fewer escalations' },
  //   ],
  // },

  // {
  //   title: 'Financial Modeling Tool',
  //   company: 'JP Morgan Chase',
  //   description: 'Built an internal Retool app for the finance team to run scenario models without engineering dependency.',
  //   tags: ['Finance', 'Retool', 'No-code'],
  //   category: 'finance',
  //   link: '/projects/financial-modeling-tool',
  //   type: 'internal',
  //   featured: false,
  //   metrics: [
  //     { value: '80%', label: 'Less eng time' },
  //   ],
  // },
  // {
  //   title: 'LLM Document Summarizer',
  //   company: 'JP Morgan Chase',
  //   description: 'Prototyped an LLM pipeline to auto-summarize lengthy compliance documents for analyst review.',
  //   tags: ['LLMs', 'Python', 'AI Agents'],
  //   category: 'ai',
  //   link: '/projects/llm-doc-summarizer',
  //   type: 'internal',
  //   featured: false,
  //   metrics: [
  //     { value: '5×', label: 'Faster doc review' },
  //   ],
  // },
];
